### PR TITLE
Improve table & colorize

### PR DESCRIPTION
**Pull request by DanielRivasMD**
Hey,

Love your work, but I felt the table needed some more life. So I custom-made a table, with space for titles and descriptions, and put some color on it. It also works with pipes. I also created a result specific type, analog to `PierError`. Looking forward to hear your comments.

Cheers

### CODE REVIEW

**Comment by Plommonsorbet** [comment]
Thanks for the pull request. The changes look good, however I just merged in another pull requests so you will need to rebase it first before I can merge.

I'm taking a break from this for a while, going to try and find a new maintainer to take over from me. Started feeling burnout after pushing myself too much this past year, however I will still be checking in once in a while to merge pull requests but most likely not that often for some time in the future.

**Comment by DanielRivasMD** [comment]
I'll take a look. I'd really interested to participate in maintaining the repo. What happened with the original maintainer?

**Comment by DanielRivasMD** [comment]
Hi again,

I rebased to the latest branch and fix some conflicts that emerged. It ought to be working as expected now.

Cheers

**Comment by Plommonsorbet** [comment]
Originally Ben created the basic framework and tool and then I built the testing, rewrote most of the code with good error handling in mind, and a few other bits. I think Ben has moved on to new projects but I still ocassionally talk to him, he's a super nice guy and very helpful. 

Would be awesome if you wanted to become a maintainer, I think I would like to see you do a few pull requests first and maybe we can have a call so I can explain some of my thought processes / historical contexts before I give you maintainer rights. :)

I unfortuntely don't really use pier almost at all anymore so I think that's also where a lot of my lack of ideas/motivation to move the project forward stems from. Mostly I just find it easier creating an emacs function or just pushing it into a shell script so I can manage it via nix to be easier.

**Pull request merged**
